services:
  generator:
    image: ghcr.io/mauckisch/opnsense-wireguard-config-generator:latest
    container_name: opnsense-wireguard-config-generator
    restart: unless-stopped
    init: true

    ports:
      - "8787:8787"
