services:
  generator:
    image: ghcr.io/mauckisch/wireforge:latest
    container_name: wireforge
    restart: unless-stopped
    init: true

    ports:
      - "8787:8787"

    volumes:
      - wireforge-data:/app/data

volumes:
  wireforge-data:
    name: wireforge-data
